version: '3'

services:  
  sqlite:
    image: 'keinos/sqlite3'
    volumes: 
      - data:/data/db
  
  backend:
    build: .
    ports:
      - '80:80'
    volumes: 
      - ./backend:/app
    env_file: 
      - ./src/utils/env/backend.env
    depends_on:
      - sqlite
      
volumes: 
  data: